"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1kvgx=2v^6gptdwu233%p*rxfsq6avaelm!l^0pp%8cgn2cxoz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'rest_framework'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


GOOGLE_APPLICATION_CREDENTIALS = {
    "type": "service_account",
    "project_id": "vision-api-421309",
    "private_key_id": "52b196de6e74c2fe2e506b2a67ad6f31a1fd031e",
    "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQD6MbZ/51Zco5b3\nMHiFO/ZOSznoqHdzJS0Eji4Qr/f7P2wJcX2MDX82PTPUhhavWfg91lFko0WtAdyp\n7w2+yGKmDdRKXF2FMScmxqi36ci13lX1bKH219eS4wPbf+h0aPyxSbColNFFXwkk\n6nXQdfcNBro6ZCWc96oD0Uc1EQHdztx+6aJ9VmZ1PB0P9WShvb6gCV4xzOmqg6eH\nyJbwNQUgMPSBalVH6vuQncPtyj50OvHhxkLyPkE8ylUIyQanYvlu6+Y+kDpCv1T9\nvqi41LQdC5jsqgSWSRAztvLIg/rg3cyBIsjIDFwXzh7ag9gACezbw8Ptzetf76bQ\nlBj4bfJPAgMBAAECggEABbSVg1QssX8fhbKKxQsJgl6PywDwfGU4Ihb18PZ6UrXv\nCkYWxVdXc86wfGO0Z7pHAW3+PCvG/nuA4zUq3JNoQH4nPazeixeEW4uDNHJ128Pe\ntPKNvPnOFjDsGRjRHbp5LLfP+gAux4Szyi44kpDmGdtx6rv26Z3yOBURKSIip0Kx\nVJ7jKU42IEQAA9e1qVz2b6/OdlKxsIL/E+eEkReZpaXHmw4IpghlSNBnlfeIVTqR\nfOSczL9edRduB24R8iuupOTfX76SBxeMUG4+o7Sdx4j9Cflj20Qyy7HF024qCfa7\nes2Cc8Wmo62RB1Q187/jEQ2xFb0Fe00++2LqXUE3/QKBgQD9iWD09nG4d1xyl9WD\nXLN7MCfaMNbv4k67HytABgPM3c6zjP9avPLPwmhJeXLDAMm912k5TwYpIFyQ3Ats\n3YU0tFo/PntCfsAQIoOyjYXFXRnZaY87Pa1y/I7VLqGwirTHk8MPTm8lx5f+QjoN\nsjXwBohK/tFMiaRCvbUBk3Jb2wKBgQD8oAU/GCxK5tAdmzOUANfv577jene6tdiq\neifsAg8tQQanPv4r8zHX1cyT0/1Ub8a6V5mkmP+IJQNJNYuampElU3JYWyJ0GQgx\nPyu0UJtVKHlQsNo8xaCoHGxJls1lzrSMalXU1X7+ajaFKa0tv1ahoPFzCS07AKak\ndTZSuAvnnQKBgANB4pcDG47tKajnPn0DkeLBSaHKAtjuJWjOC7Y03ZOiPeecpiM6\nTjxRGRnoj4rl1bG0tMthsoiQu9+4lAUAC5gTwR0S5m6CRmFusBZ5LwDMI2rhqk9u\niW3yxLsEcFteTNhLk7P8o/zuRYukui423e6JhvK/t1yuYAfjfBHbHRsFAoGBAOHD\n/IxThRn3Rpx+3ExzqIeNO2o+Q4wIAbbw7oabnIab619CC5Kph6zVNDwUovx33Eki\nCnwwA4XfVh1yDe5AHmEWP0U5RQQubsTcKKm/s+IaBrkXJCJVl+tFY30smSlX3sDy\nMvy/Q/wIXesJwOv2aGyP0dg1pkdpoIOvALpSIsl9AoGAPRgtm4FYAjf3aZwaF69i\n8Rpa6zKlBS921dQiyev7SVrcFCHxCMV5MsCoFUMQvOJOIPsuJoQVAVuT8966dWex\ne5xWUvzJZXthWEamZTRtjOhZDFtNYmr936RVVgRDj1p2A7jmEHYW9IPGa/icANEa\nRvw9Me8FP31+AmBNEFCBNWA=\n-----END PRIVATE KEY-----\n",
    "client_email": "cloud-vision-api@vision-api-421309.iam.gserviceaccount.com",
    "client_id": "108218808334953793324",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/cloud-vision-api%40vision-api-421309.iam.gserviceaccount.com",
    "universe_domain": "googleapis.com"
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
